//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemasVirtuales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int id_Admi { get; set; }
        public string correo { get; set; }
        public string pwd { get; set; }
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string ap_pat { get; set; }
        public string ap_mat { get; set; }
        public string puesto { get; set; }
        public Nullable<int> rol { get; set; }
    }
}
