//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemasVirtuales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutores_Alumnos
    {
        public int id_relacion { get; set; }
        public Nullable<int> id_Alumno { get; set; }
        public Nullable<int> id_Docente { get; set; }
        public Nullable<int> id_Semetre { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Docentes Docentes { get; set; }
        public virtual Semestre Semestre { get; set; }
    }
}
